# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main","backend"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: set execution rights to gradlew
      run: chmod +x Forráskód/Backend/backend/gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        build-root-directory: Forráskód/Backend/backend/
    - name: deepen clone
      run: git fetch --all --unshallow
    - name: Deploy to Heroku
      # You may pin to the exact commit or the version.
      # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Email from Heroku Account
        heroku_email: szt2otokov@vasvari.org
        # The appname to use for deploying/updating
        heroku_app_name: boola-backend
        # Contents of the Procfile to save and deploy
        procfile: "web: java -jar Forráskód\\Backend\\backend\\build\\libs\\backend-0.0.1.jar"
        # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
        dynamicFiles: true
        buildpacks: "[\"https://github.com/heroku/heroku-buildpack-gradle.git\"]"
        
