# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main","backend"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: set execution rights to gradlew
      run: chmod +x ./gradlew
      working-directory: Forráskód/Backend/backend
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        build-root-directory: Forráskód/Backend/backend
   # - name: deepen clone
    #  run: git fetch --all --unshallow
     # working-directory: Forráskód/Backend/backend
    - name: Deploy to Heroku
      uses: behe/heroku-build@v1.2
      with:
          # Name of Heroku application
          app-name: boola-backend
          # API key with the deploy role
          api-key: ${{secrets.HEROKU_API_KEY}}
          # Directory to upload
          path: Forráskód/Backend/backend
              
