
name: Deploy server to Heroku

on:
  schedule:
    - cron: '0 0 * * 5'
  pull_request:
    branches: ['backend']
    types:
      - closed

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: backend
    steps:
    - uses: actions/checkout@v3
    - name: Heroku Docker Container Deploy
  # You may pin to the exact commit or the version.
  # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
      uses: lucassarcanjo/heroku-deploy@2.1.17
      with:
    # Email Linked to your Heroku Account
        email: szt2otokov@vasvari.org
    # Your Heroku API Key
        api_key: ${{secrets.HEROKU_API_KEY}}
    # Your Heroku App Name
        app_name: boola-backend
    # Dokerfile path
        dockerfile_path: Forráskód/Backend/backend
